#! /bin/bash

# repo=$1
verbosity=${2-"$1"}
destination=$(fenrir-getroot)
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$verbosity" "TR: Running on tricky logs.."

# Setup logs
dir=$(fenrir-tmp -d 2> /dev/null || mktemp -dd)

pushd "$dir" &> /dev/null
{
  echo "[ ERROR ] 11:12:2024 07 PANIC"
  echo "[ DEBUG ] 12:12:2024 2 БУГАГАШЕНЬКИ"
  echo "[ INFО ] 12:12:2024 4 RELOAD"
  echo "[ WARNING ] 13:12:2024 1000000000001 FAILURE"
} > log.log
popd &> /dev/null

# Running up
if ! "$destination/bash/logs/parse-logs.sh" -o up -l 3 "$dir" > "$out" 2> "$err"; then
    fenrir-log err "$verbosity" "TR: Script execution has failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

content=$(cat "$out")

if [ "$(echo "$content" | wc -l)" -ne 1 ]; then
    fenrir-log err "$verbosity" "TR: Expected 1 line but got '$(echo "$content" | wc -l)'"
    exit 9
fi

if ! [ "$(echo "$content" | sed '1p;d')" = "[ WARNING ] 13:12:2024 1000000000001 FAILURE" ]; then
    fenrir-log err "$verbosity" "TR: Wrong output:"
    fenrir-log err "$verbosity" "    Expected <[ WARNING ] 13:12:2024 1000000000001 FAILURE>"
    fenrir-log err "$verbosity" "    Got <$(echo "$content" | sed '1p;d')>"
    exit 1
fi

# Running down
if ! "$destination/bash/logs/parse-logs.sh" --lines 33 --order down "$dir" > "$out" 2> "$err"; then
    fenrir-log err "$verbosity" "TR: Script execution has failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

content=$(cat "$out")

if [ "$(echo "$content" | wc -l)" -ne 1 ]; then
    fenrir-log err "$verbosity" "TR: Expected 1 line but got '$(echo "$content" | wc -l)'"
    exit 9
fi

if ! [ "$(echo "$content" | sed '1p;d')" = "[ WARNING ] 13:12:2024 1000000000001 FAILURE" ]; then
    fenrir-log err "$verbosity" "TR: Wrong output!"
    fenrir-log err "$verbosity" "    Expected <[ WARNING ] 13:12:2024 1000000000001 FAILURE>"
    fenrir-log err "$verbosity" "    Got <$(echo "$content" | sed '1p;d')>"
    exit 1
fi


fenrir-add-points 30

fenrir-log succ "$verbosity" "TR: PASSED"
