#! /bin/bash

v=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$v" "CS: Checking codestyle.."

if ! python3 scripts/run-clang-format.py -r include > "$out" 2> "$err"; then
    fenrir-log err  "$v" "CS: Your code has bad smell"
    fenrir-log warn "$v" "CS: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "CS: <stderr>" "$(cat "$err")"
    exit 55
fi

if ! python3 scripts/run-clang-format.py -r src > "$out" 2> "$err"; then
    fenrir-log err  "$v" "CS: Your code has bad smell"
    fenrir-log warn "$v" "CS: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "CS: <stderr>" "$(cat "$err")"
    exit 55
fi

if ! python3 scripts/run-clang-format.py -r test > "$out" 2> "$err"; then
    fenrir-log err  "$v" "CS: Your code has bad smell"
    fenrir-log warn "$v" "CS: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "CS: <stderr>" "$(cat "$err")"
    exit 55
fi

fenrir-log info "$v" "CS: Generate 'compile_commands.json' for clang-tidy.."

if ! cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug > "$out" 2> "$err"; then
    fenrir-log err  "$v" "CS: Your code has bad smell"
    fenrir-log warn "$v" "CS: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "CS: <stderr>" "$(cat "$err")"
    exit 55
fi

if ! python3 scripts/run-clang-tidy.py -warnings-as-errors '*' -p build -use-color > "$out" 2> "$err"; then
    fenrir-log err  "$v" "CS: Your code has bad smell"
    fenrir-log warn "$v" "CS: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "CS: <stderr>" "$(cat "$err")"
    exit 55
fi

rm -fr build

fenrir-log succ "$v" "CS: Your codestyle is perfect! (Maybe..)"
