#! /bin/bash

v=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$v" "S4: Running tests for stage-4.."

fenrir-log info "$v" "S4: Running CMake.."

if ! cmake -S . -B build -DCODE_COVERAGE_VERBOSE=ON -DCMAKE_BUILD_TYPE=Debug > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S4: Something went wrong"
    fenrir-log warn "$v" "S4: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S4: <stderr>" "$(cat "$err")"
    exit 55
fi

if ! cmake --build build --target stage-4 > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S4: Something went wrong"
    fenrir-log warn "$v" "S4: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S4: <stderr>" "$(cat "$err")"
    exit 55
fi

fenrir-log info "$v" "S4: Running comparison-tests.."

if ! cmake --build build --target comparison > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S4: Something went wrong"
    fenrir-log warn "$v" "S4: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S4: <stderr>" "$(cat "$err")"
    exit 55
fi

rm -fr build

fenrir-add-points 40

fenrir-log succ "$v" "S4: PASSED"
