#! /bin/bash

v=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$v" "S2: Running tests for stage-2.."

fenrir-log info "$v" "S2: Running CMake.."

if ! cmake -S . -B build -DCODE_COVERAGE_VERBOSE=ON -DCMAKE_BUILD_TYPE=Debug > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S2: Something went wrong"
    fenrir-log warn "$v" "S2: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S2: <stderr>" "$(cat "$err")"
    exit 55
fi

if ! cmake --build build --target stage-2 > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S2: Something went wrong"
    fenrir-log warn "$v" "S2: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S2: <stderr>" "$(cat "$err")"
    exit 55
fi

rm -fr build

fenrir-add-points 20

fenrir-log succ "$v" "S2: PASSED"
