#! /bin/bash

v=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$v" "S3: Running tests for stage-3.."

fenrir-log info "$v" "S3: Running CMake.."

if ! cmake -S . -B build -DCODE_COVERAGE_VERBOSE=ON -DCMAKE_BUILD_TYPE=Debug > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S3: Something went wrong"
    fenrir-log warn "$v" "S3: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S3: <stderr>" "$(cat "$err")"
    exit 55
fi

if ! cmake --build build --target stage-3 > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S3: Something went wrong"
    fenrir-log warn "$v" "S3: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S3: <stderr>" "$(cat "$err")"
    exit 55
fi

fenrir-log info "$v" "S3: Running comparison-tests.."

if ! cmake --build build --target comparison > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S3: Something went wrong"
    fenrir-log warn "$v" "S3: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S3: <stderr>" "$(cat "$err")"
    exit 55
fi

rm -fr build

fenrir-add-points 30

fenrir-log succ "$v" "S3: PASSED"
