#! /bin/bash

v=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$v" "S1: Running tests for stage-1.."

fenrir-log info "$v" "S1: Running CMake.."

if ! cmake -S . -B build -DCODE_COVERAGE_VERBOSE=ON -DCMAKE_BUILD_TYPE=Debug > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S1: Something went wrong"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"
    exit 55
fi

if ! cmake --build build --target stage-1 > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S1: Something went wrong"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"
    exit 55
fi

rm -fr build

fenrir-add-points 10

fenrir-log succ "$v" "S1: PASSED"
