#! /bin/bash

points=10
verbosity=$1


fenrir-log info "$verbosity" "P4: Validating commits tree.."

if ! fenrir-change-branch "$verbosity" "7" || \
   ! fenrir-change-branch "$verbosity" "8" || \
   ! fenrir-change-branch "$verbosity" "9"; then
        fenrir-log err "$verbosity" "P4: Terminating.."
        exit 1
fi

if ! git branch -a --contains 9~2 | grep -q 7; then
    fenrir-log err "$verbosity" "P4: Incorrect rebase or extra commits present"
    exit 1
fi

if [ "$(fenrir-commit-name "9")"   = "16" ] && \
   [ "$(fenrir-commit-name "9~1")" = "15" ] && \
   [ "$(fenrir-commit-name "9~2")" = "18" ]; then
        fenrir-add-points "$points"
else
    fenrir-log err "$verbosity" "P4: Incorrect commit messages"
    exit 1
fi

fenrir-log succ "$verbosity" "P4: PASSED"
