#! /bin/bash

points=10
repo=$1
verbosity=$2


fenrir-log info "$verbosity" "P6: Validating commits tree.."

if ! fenrir-branch-exists "$verbosity" "$repo" "11"; then
    fenrir-log err "$verbosity" "P6: Terminating.."
    exit 1
fi

if [[ '12a0b906' == "$(fenrir-commit-hash "11")"*  ]]; then
    fenrir-log err "$verbosity" "P6: Invalid last commit"
    fenrir-log err "$verbosity" "P6: Expected <$(fenrir-commit-hash "11")> to be prefix of <12a0b906>"
    exit 1
fi

fenrir-add-points "$points"
fenrir-log succ "$verbosity" "P6: PASSED"
