#! /bin/bash

points=20
repo=$1
verbosity=$2
out="/var/fenrir/out"
err="/var/fenrir/err"


fenrir-log info "$verbosity" "P3: Validating commits tree.."

if ! fenrir-branch-exists "$verbosity" "$repo" "5"   || \
   ! fenrir-branch-exists "$verbosity" "$repo" "6"; then
        fenrir-log err "$verbosity" "P3: Terminating.."
        exit 1
fi

if ! fenrir-change-branch "$repo" "$verbosity" "5"; then
    fenrir-log err "$verbosity" "P3: Terminating.."
    exit 1
fi

fenrir-log info "$verbosity" "P3: Merging.."

already=("modify/delete" "content")
curr=()
success=0

####################################################################
if git merge 6 > "$out" 2> "$err"; then
    fenrir-log err "$verbosity" "P3: No error occurred"
    exit 1
fi

while IFS= read -r type; do
    fenrir-log info "$verbosity" "P3: Merge conflict's type is ($type)"
    curr+=("$type")
    already+=("$type")

    for forbidden in "${already[@]}"; do
        if [ "$type" != "$forbidden" ]; then
            success=1
        fi
    done

done < <(sed -nE 's/.*CONFLICT \((.*)\).*/\1/p' "$out")

if [ "$success" -ne 1 ]; then
    fenrir-log err "$verbosity" "P3: Such type <${curr[*]}> of MC occurred in previous parts"
    fenrir-log warn "$verbosity" "<stdout> $(cat "$out")"
    fenrir-log err "$verbosity" "<stderr> $(cat "$err")"
    exit 1
fi

git merge --abort

fenrir-add-points "$points"

fenrir-log succ "$verbosity" "P3: PASSED"
