#! /bin/bash

points=10
verbosity=$1


fenrir-log info "$verbosity" "P6: Validating commits tree.."

if ! fenrir-change-branch "$verbosity" "11"; then
    fenrir-log err "$verbosity" "P6: Terminating.."
    exit 1
fi

real=$(fenrir-commit-hash "11")
if [[ ! 12a0b906 == $real*  ]]; then
    fenrir-log err "$verbosity" "P6: Invalid last commit"
    fenrir-log err "$verbosity" "P6: Expected <$real> to be prefix of <12a0b906>"
    exit 1
fi

fenrir-add-points "$points"
fenrir-log succ "$verbosity" "P6: PASSED"
