#! /bin/bash

points=10
verbosity=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$verbosity" "P10: Validating commits tree.."

if ! fenrir-change-branch "$verbosity" "16"; then
    fenrir-log err "$verbosity" "P10: Terminating.."
    exit 1
fi

fenrir-log info "$verbosity" "P10: Validating file mode.."

if [ "$(fenrir-file-type win.sh)" != '100755' ]; then
    fenrir-log err "$verbosity" "P10: Invalid file mode"
    exit 1
fi

fenrir-log info "$verbosity" "P10: Executing script.."

if ! ./win.sh > "$out" 2> "$err"; then
    fenrir-log err "$verbosity"  "Failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
    exit 1
fi

if [ "$(cat "$out")" != "HI" ] &&
   [ -n "$(cat "$err")" ]; then
    fenrir-log err "$verbosity"  "Something went wrong:"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
    exit 1
fi

fenrir-add-points "$points"

fenrir-log succ "$verbosity" "P10: PASSED"
