#! /bin/bash

points=10
repo=$1
verbosity=$2


fenrir-log info "$verbosity" "P7: Validating commits tree.."

if ! fenrir-branch-exists "$verbosity" "$repo" "12"; then
        fenrir-log err "$verbosity" "P7: Terminating.."
        exit 1
fi

if [ "$(fenrir-commit-name "12")" != '27' ]; then
        fenrir-log err "$verbosity" "P7: Invalid last commit"
        fenrir-log err "$verbosity" "P7: Expected <$(fenrir-commit-name "12")> to be <27>"
        exit 1
fi

real=$(fenrir-commit-parent "12")
if [[ ! 5c468f81 == $real*  ]]; then
        fenrir-log err "$verbosity" "P7: Invalid last commit"
        fenrir-log err "$verbosity" "P7: Expected <$real> to be prefix of <5c468f81>"
        exit 1
fi

fenrir-add-points "$points"
fenrir-log succ "$verbosity" "P7: PASSED"
