#! /bin/bash

points=10
repo=$1
verbosity=$2
out="/var/fenrir/out"
err="/var/fenrir/err"


log info "$verbosity" "P5: Validating commits tree.."

if ! branch-exists "$verbosity" "$repo" "10"; then
        log err "$verbosity" "P5: Terminating.."
        exit 1
fi

if ! git branch -a --contains origin/9~2 | grep -q 7; then
    log err "$verbosity" "P5: Incorrect rebase or extra commits present"
    exit 1
fi

if [ "$(commit-name "origin/10~0")" != 'Revert "21"' ] || \
   [ "$(commit-name "origin/10~1")" != "23" ] || \
   [ "$(commit-name "origin/10~2")" != "22" ] || \
   [ "$(commit-name "origin/10~3")" != "21" ]; then
        log err "$verbosity" "P5: You have not undone the changes"
        exit 1
fi

log info "$verbosity" "P5: Validating files content.."

if git show -s --format=%b origin/10 | grep "This reverts commit abcee" > "$out" 2> "$err"; then
    if git show origin/10:5.txt > "$out" 2> "$err"; then
        content=$(cat "$out")

        if [ "$(echo "$content" | wc -w)" -eq 3 ] && \
           [ "$(echo "$content" | sed '1p;d')" = "1" ] && \
           [ "$(echo "$content" | sed '2p;d')" = "2" ] && \
           [ "$(echo "$content" | sed '3p;d')" = "3" ]; then
                add-points "$points"
        else
            log err "$verbosity" "P5 Incorrect files content"
            log warn "$verbosity" "<stdout>" "$(cat "$out")"
            log err "$verbosity" "<stderr>" "$(cat "$err")"
            exit 1
        fi
    else
        log err "$verbosity" "P5: Error while reading file"
        log warn "$verbosity" "<stdout>" "$(cat "$out")"
        log err "$verbosity" "<stderr>" "$(cat "$err")"
        exit 1
    fi
else
    log err "$verbosity" "P5: Incorrect commit body"
    log warn "$verbosity" "<stdout>" "$(cat "$out")"
    log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

log succ "$verbosity" "P5: PASSED"
