#! /bin/bash

points=10
verbosity=$1
out="/var/fenrir/out"
err="/var/fenrir/err"


fenrir-log info "$verbosity" "P5: Validating commits tree.."

if ! fenrir-change-branch "$verbosity" "10"; then
    fenrir-log err "$verbosity" "P5: Terminating.."
    exit 1
fi

if ! git branch -a --contains 9~2 | grep -q 7; then
    fenrir-log err "$verbosity" "P5: Incorrect rebase or extra commits present"
    exit 1
fi

if [ "$(fenrir-commit-name "10~0")" != 'Revert "21"' ] || \
   [ "$(fenrir-commit-name "10~1")" != "23" ] || \
   [ "$(fenrir-commit-name "10~2")" != "22" ] || \
   [ "$(fenrir-commit-name "10~3")" != "21" ]; then
        fenrir-log err "$verbosity" "P5: You have not undone the changes"
        exit 1
fi

fenrir-log info "$verbosity" "P5: Validating files content.."

if git show -s --format=%b 10 | grep "This reverts commit abcee" > "$out" 2> "$err"; then
    if git show 10:5.txt > "$out" 2> "$err"; then
        content=$(cat "$out")

        if [ "$(echo "$content" | wc -w)" -eq 3 ] && \
           [ "$(echo "$content" | sed '1p;d')" = "1" ] && \
           [ "$(echo "$content" | sed '2p;d')" = "2" ] && \
           [ "$(echo "$content" | sed '3p;d')" = "3" ]; then
                fenrir-add-points "$points"
        else
            fenrir-log err "$verbosity" "P5 Incorrect files content"
            fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
            fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
            exit 1
        fi
    else
        fenrir-log err "$verbosity" "P5: Error while reading file"
        fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
        fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
        exit 1
    fi
else
    fenrir-log err "$verbosity" "P5: Incorrect commit body"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

fenrir-log succ "$verbosity" "P5: PASSED"
