#! /bin/bash

points=10
repo=$1
verbosity=$2
out="/var/fenrir/out"
err="/var/fenrir/err"


fenrir-log info "$verbosity" "P1: Validating commits tree.."

if ! fenrir-branch-exists "$verbosity" "$repo" "1" || \
   ! fenrir-branch-exists "$verbosity" "$repo" "2"; then
        fenrir-log err "$verbosity" "P1: Terminating.."
        exit 1
fi

merge_commit=$(git log --merges --format="%h" 1)

if [ -z "$merge_commit" ]; then
    fenrir-log err "$verbosity" "P1: You haven't merged branch"
    exit 1
fi

if ! [ "$merge_commit" = "$(fenrir-commit-hash "1~0")" ]; then
    fenrir-log err "$verbosity" "P1: Expected the merge commit to be the latest"
    exit 1
fi

merge_commit=$(git log --merges --format="%h" 2)

if [ -n "$merge_commit" ]; then
    fenrir-log err "$verbosity" "P1: Encountered merge commits in branch <2>"
    exit 1
fi

if ! [ "$(fenrir-commit-name "1~0")" = "3" ]; then
    fenrir-log err "$verbosity" "P1: Expected commit message to be <3>"
    exit 1
fi

fenrir-log info "$verbosity" "P1: Validating files content.."

if git show 1:1.txt > "$out" 2> "$err"; then
    content=$(cat "$out")

    if [ "$(echo "$content" | wc -w)" -eq 3 ] && \
       [ "$(echo "$content" | sed '1p;d')" = "3" ] && \
       [ "$(echo "$content" | sed '2p;d')" = "2" ] && \
       [ "$(echo "$content" | sed '3p;d')" = "1" ]; then
            if ! git show 1:2.txt > "$out" 2> "$err"; then
                fenrir-add-points "$points"
            else
                fenrir-log err "$verbosity" "P1: Incorrect files content"
                fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
                fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
                exit 1
            fi
    else
        fenrir-log err "$verbosity" "P1: Incorrect files content"
        fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
        fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
        exit 1
    fi
else
    fenrir-log err "$verbosity" "P1: Something went wrong while reading the file"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

fenrir-log succ "$verbosity" "P1: PASSED"
