#! /bin/bash

points=10
repo=$1
verbosity=$2
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$verbosity" "P9: Validating commits tree.."

if ! fenrir-branch-exists "$verbosity" "$repo" "14" || \
   ! fenrir-branch-exists "$verbosity" "$repo" "15"; then
        fenrir-log err "$verbosity" "P9: Terminating.."
        exit 1
fi

real1=$(fenrir-commit-hash "14~1")
real2=$(fenrir-commit-hash "15~0")
if [[ "$(fenrir-commit-name "14~0")" != '6003' ]] || \
   [[ "$(fenrir-commit-name "14~1")" != '6006' ]] || \
   [[ ! 4e7b0f2b == $real1*  ]] || \
   [[ ! 3319f09d == $real2*  ]]; then
        fenrir-log err "$verbosity" "P9: Invalid commit tree"
        exit 1
fi

fenrir-log info "$verbosity" "P9: Validating file content.."

if git show 14:9.txt > "$out" 2> "$err"; then
    content=$(cat "$out")

    if [ "$(echo "$content" | wc -w)" -eq 4 ] && \
       [ "$(echo "$content" | sed '1p;d')" = "5" ] && \
       [ "$(echo "$content" | sed '2p;d')" = "4" ] && \
       [ "$(echo "$content" | sed '3p;d')" = "3" ] && \
       [ "$(echo "$content" | sed '4p;d')" = "2" ]; then
            fenrir-add-points "$points"
    else
        fenrir-log err "$verbosity" "P9: Incorrect files content"
        fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
        fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
        exit 1
    fi
else
    fenrir-log err "$verbosity" "P9: Something went wrong while reading the file"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi


fenrir-log succ "$verbosity" "P9: PASSED"
