#! /bin/bash

points=30
repo=$1
verbosity=$2
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$verbosity" "P11: Validating commits tree.."

if ! fenrir-change-branch "$repo" "$verbosity" "17"; then
    fenrir-log err "$verbosity" "P11: Terminating.."
    exit 1
fi

fenrir-log info "$verbosity" "P11: Searching script.."

if ! [ -x "install" ]; then
    fenrir-log err "$verbosity" "P11: 'install' was not found"
    exit 1
fi

fenrir-log succ "$verbosity" "P11: 'install' was found"


fenrir-log info "$verbosity" "P11: Saving '.git/hooks'.."

backup=$(mktemp -d)

cp -r .git/hooks/ "$backup"

function backup_terminate {
    msg=$1

    fenrir-log err "$verbosity"  "$msg"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"

    rm -r .git/hooks
    mv "$backup/hooks" .git/

    if git status | grep -q bugaga; then
        git restore --staged bugaga
    fi

    if [ -f bugaga ]; then
        rm bugaga
    fi

    exit 1
}


fenrir-log info "$verbosity" "P11: Installing hooks.."

if ! ./install > "$out" 2> "$err"; then
    fenrir-log err "$verbosity"  "Failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity"  "<stderr>" "$(cat "$err")"
    exit 1
fi

fenrir-log succ "$verbosity" "P11: Installed"

fenrir-log info "$verbosity" "P11: Creating file 'bugaga'.."
touch bugaga

fenrir-log info "$verbosity" "P11: Running 'git add bugaga'.."
git add bugaga

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"BAD MESSAGE\"'.."
if git commit -m "BAD MESSAGE" > "$out" 2> "$err"; then
    backup_terminate "File has been commited!"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[FIX] BAD\"'.."
if git commit -m "[FIX] BAD" > "$out" 2> "$err"; then
    backup_terminate "File has been commited!"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ АDD ] Tricky\"'.."
if git commit -m "[ АDD ] Tricky" > "$out" 2> "$err"; then
    backup_terminate "File has been commited! ('A' is cyrillic)"
    exit 1
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ]Tricky\"'.."
if git commit -m "[ ADD ]Tricky" > "$out" 2> "$err"; then
    backup_terminate "File has been commited!"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

fenrir-log info "$verbosity" "P11: Running 'git commit -m \" [ ADD ] Tricky\"'.."
if git commit -m " [ ADD ] Tricky" > "$out" 2> "$err"; then
    backup_terminate "File has been commited!"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ] Triсky\"'.."
if git commit -m "[ ADD ] Triсky" > "$out" 2> "$err"; then
    backup_terminate "File has been commited! ('с' is cyrillic)"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ ADD ] Good\"'.."
if ! git commit -m "[ ADD ] Good" > "$out" 2> "$err"; then
    backup_terminate "File has not been commited!"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

git reset --soft HEAD~1

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ FIX ] Go0od\"'.."
if ! git commit -m "[ FIX ] Good" > "$out" 2> "$err"; then
    backup_terminate "File has not been commited!"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

git reset --soft HEAD~1

fenrir-log info "$verbosity" "P11: Running 'git commit -m \"[ DEL ] 1G1o1O1d1\"'.."
if ! git commit -m "[ DEL ] 1G1o1O1d1" > "$out" 2> "$err"; then
    backup_terminate "File has not been commited!"
fi
fenrir-log succ "$verbosity" "P11: Hook works correct"

git reset --hard HEAD~1

fenrir-add-points "$points"

rm -r .git/hooks
mv "$backup/hooks" .git/

fenrir-log succ "$verbosity" "P11: PASSED"

