#! /bin/bash

points=10
verbosity=$1
out="/var/fenrir/out"
err="/var/fenrir/err"


fenrir-log info "$verbosity" "P2: Validating commits tree.."

if ! fenrir-change-branch "$verbosity" "4" || \
   ! fenrir-change-branch "$verbosity" "3"; then
        fenrir-log err "$verbosity" "P2: Terminating.."
        exit 1
fi

fenrir-change-branch "$verbosity" "task0" &> /dev/null

merge_commit=$(git log --merges --format="%h" 4)

if [ -n "$merge_commit" ]; then
    fenrir-log err "$verbosity" "P2: There is a merge commit in branch <4>: <$merge_commit>"
    exit 1
fi

merge_commit=$(git log --merges --format="%h" 3)

if [ -n "$merge_commit" ]; then
    fenrir-log err "$verbosity" "P2: There is a merge commit in branch <3>: <$merge_commit>"
    exit 1
fi

found=0

for (( i = 0; i < 3; i++ )); do
    if git branch -a --contains "4~$i" | grep -q 3; then
        hash=$(fenrir-commit-hash "4~$i")
        branch3=$(fenrir-commit-hash "3")

        if ! [ "$hash" = "$branch3" ]; then
            fenrir-log err "$verbosity" "P2: Expected commit <$hash> to equal to <$branch3>"
            exit 1
        fi

        found=1
        break
    fi
done

if [ "$found" -ne 1 ]; then
    fenrir-log err "$verbosity" "P2: Branch 4 contains far too many commits (Branch 3 was not found)"
fi

fenrir-log info "$verbosity" "P2: Validating files content.."

if git show 4:3 > "$out" 2> "$err"; then
    content=$(cat "$out")

    if [ "$(echo "$content" | wc -w)" -eq 2 ] && \
       [ "$(echo "$content" | sed '1p;d')" = "1" ] && \
       [ "$(echo "$content" | sed '2p;d')" = "3" ]; then
            if git show 4:4 > "$out" 2> "$err"; then
                content=$(cat "$out")

                if [ "$(echo "$content" | wc -w)" -eq 2 ] && \
                   [ "$(echo "$content" | sed '1p;d')" = "1" ] && \
                   [ "$(echo "$content" | sed '2p;d')" = "4" ]; then
                        fenrir-add-points "$points"
                else
                    fenrir-log err "$verbosity" "P2:2 Incorrect files content"
                    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
                    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
                    exit 1
                fi
            else
                fenrir-log err "$verbosity" "P2: Something went wrong while reading the file"
                fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
                fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
                exit 1
            fi
    else
        fenrir-log err "$verbosity" "P2:1 Incorrect files content"
        fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
        fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
        exit 1
    fi
else
    fenrir-log err "$verbosity" "P2: Something went wrong while reading the file"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

fenrir-log succ "$verbosity" "P2: PASSED"
