#! /bin/bash

function clean {
    pushd "$(fenrir-getroot)" &> /dev/null
    rm -r coverage &> /dev/null
    rm -r results &> /dev/null
    rm -r build &> /dev/null
    rm -r cmake/CodeCoverage.cmake &> /dev/null
    popd &> /dev/null
}

v=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$v" "S1: Running test 1.."



if ! cmake -S . -B build > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S1: Failed to run CMake"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"

    clean
    exit 11
fi

if ! cmake --build build --target train > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S1: Failed to build with CMake"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"

    clean
    exit 11
fi

if ! [ -d results ]; then
    fenrir-log err "$v" "S1: Directory 'results' was not found"

    clean
    exit 6
fi

cd results

if ! [ -f train ]; then
    fenrir-log err "$v" "S1: File 'train' was not found"

    clean
    exit 6
fi

if ! ./train 11 > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S1: Binary file execution failed"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"

    clean
    exit 11
fi

if ! { cat "$out" | grep -q "Winner is stormfly"; }; then
    fenrir-log err  "$v" "S1: Wrong winner - you might have modified files"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"

    clean
    exit 11
fi

if ! ./train 6 > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S1: Binary file execution failed"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"

    clean
    exit 6
fi

if ! { cat "$out" | grep -q "Winner is trench"; }; then
    fenrir-log err  "$v" "S1: Wrong winner - you might have modified files"
    fenrir-log warn "$v" "S1: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S1: <stderr>" "$(cat "$err")"

    clean
    exit 6
fi

clean
fenrir-add-points 15
fenrir-log succ "$v" "S1: PASSED"

