#! /bin/bash

function clean {
    pushd "$(fenrir-getroot)" &> /dev/null
    rm -r coverage &> /dev/null
    rm -r results &> /dev/null
    rm -r build &> /dev/null
    rm -r cmake/CodeCoverage.cmake &> /dev/null
    popd &> /dev/null
}

function tests {
    fenrir-log info "$v" "S2-2: Running test 2 for profile $1.."

    if ! cmake -S . -B build -D$1=ON > "$out" 2> "$err"; then
        fenrir-log err  "$v" "S2-2: Failed to run CMake"
        fenrir-log warn "$v" "S2-2: <stdout>" "$(cat "$out")"
        fenrir-log err  "$v" "S2-2: <stderr>" "$(cat "$err")"

        clean
        exit 11
    fi

    if ! cmake --build build > "$out" 2> "$err"; then
        fenrir-log err  "$v" "S2-2: Failed to build with CMake"
        fenrir-log warn "$v" "S2-2: <stdout>" "$(cat "$out")"
        fenrir-log err  "$v" "S2-2: <stderr>" "$(cat "$err")"

        clean
        exit 11
    fi

    if ! { pushd build && make test; } > "$out" 2> "$err"; then
        fenrir-log err  "$v" "S2-2: Tests execution has failed"
        fenrir-log warn "$v" "S2-2: <stdout>" "$(cat "$out")"
        fenrir-log err  "$v" "S2-2: <stderr>" "$(cat "$err")"

        clean
        exit 11
    fi

    popd &> /dev/null

    fenrir-log succ "$v" "S2-2: PASSED"
}

v=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$v" "S2-2: Running stage 2 test 2 (coverage).."

if ! cmake -S . -B build -DDAY=ON > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S2-2: Failed to run CMake"
    fenrir-log warn "$v" "S2-2: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S2-2: <stderr>" "$(cat "$err")"

    clean
    exit 11
fi


if ! cmake --build build --target coverage > "$out" 2> "$err"; then
    fenrir-log err  "$v" "S2-2: Failed to build with CMake"
    fenrir-log warn "$v" "S2-2: <stdout>" "$(cat "$out")"
    fenrir-log err  "$v" "S2-2: <stderr>" "$(cat "$err")"

    clean
    exit 11
fi


if [ ! -d coverage ]; then
    fenrir-log err "$v" "S2-2: Directory 'coverage' was not found"

    clean
    exit 6
fi 


if [ ! -f coverage/index.html ]; then
    fenrir-log err "$v" "S2-2: Coverage report was not found"

    clean
    exit 6
fi

clean

fenrir-add-points 40
fenrir-log succ "$v" "S2-2: PASSED"
