#! /bin/bash

verbosity=$1
out="/var/fenrir/out"
err="/var/fenrir/err"

fenrir-log info "$verbosity" "SR: Running setup script.."

if ! [ -x "install.sh" ]; then
    fenrir-log err "$verbosity" "SR: 'install.sh' was not found or is not executable"
    exit 3
fi

if ! ./install.sh > "$out" 2> "$err"; then
    fenrir-log err  "$verbosity" "SR: Script execution has failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err  "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

repo_cnt=$(git submodule foreach --recursive git remote -v | wc -l)

if [ "$repo_cnt" -ne 9 ]; then
    fenrir-log err "$verbosity" "SR: Wrong submodules count"
    fenrir-log err "$verbosity" "Expected <3>"
    fenrir-log err "$verbosity" "Got <$(( repo_cnt / 3 ))>"
    exit 7
fi

if ! [ -d "server" ]; then
    fenrir-log err "$verbosity" "SR: directory 'server' was not found"
    exit 4
fi

if ! [ -d "server/lib" ]; then
    fenrir-log err "$verbosity" "SR: directory 'server' was not found"
    exit 5
fi

if ! [ -d "server/cfgs" ]; then
    fenrir-log err "$verbosity" "SR: directory 'server' was not found"
    exit 6
fi

fenrir-log succ "$verbosity" "SR: Done"
