#! /bin/bash

verbosity=$2

fenrir-log info "$verbosity" "RR: Validating root readme.."

if ! [ -f "../README.md" ]; then
    fenrir-log err "$verbosity" "RR: Root README does not exist"
    exit 5
fi

fenrir-log succ "$verbosity" "RR: PASSED"
