#! /bin/bash

# repo=$1
verbosity=$2
destination=$(fenrir-getroot)

fenrir-log info "$verbosity" "BM: Running on broken csv (no LF).."

# Setup logs
src="/etc/fenrir/in_broken.csv"
l="/etc/fenrir/l_broken.csv"
u="/etc/fenrir/u_broken.csv"

out="/var/fenrir/out"
err="/var/fenrir/err"

out_l="$HOME/l.csv"
out_u="$HOME/u.csv"

cp "$src" "$HOME/in.csv"

echo "Бугагашеньки" > "$out_u"
echo "Buzzinga" > "$out_l"

if ! "$destination/bash/lu/decomposition.sh" "$HOME/in.csv" "$out_l" "$out_u" "1" > "$out" 2> "$err"; then
    fenrir-log err "$verbosity" "BM: Script execution has failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

if ! diff --minimal "$HOME/in.csv" "$src"; then
    fenrir-log err "$verbosity" "BM: You have modified source matrix"
    exit 4
fi

if ! diff --minimal "$out_l" "$l"; then
    fenrir-log err "$verbosity" "BM: Wrong L matrix"
    exit 3
fi

if ! diff --minimal "$out_u" "$u"; then
    fenrir-log err "$verbosity" "BM: Wrong U matrix"
    exit 2
fi

fenrir-log succ "$verbosity" "BM: PASSED"
