#! /bin/bash

# repo=$1
verbosity=$2
destination=$(fenrir-getroot)

fenrir-log info "$verbosity" "SM: Running on small matrix (3x3).."

# Setup logs
src="/etc/fenrir/in_small.csv"
l="/etc/fenrir/l_small.csv"
u="/etc/fenrir/u_small.csv"

out="/var/fenrir/out"
err="/var/fenrir/err"

out_l="$HOME/l.csv"
out_u="$HOME/u.csv"

in_matrix=$(fenrir-tmp 2> /dev/null || mktemp)
cp "$src" "$in_matrix"

if ! "$destination/bash/lu/decomposition.sh" "$in_matrix" "$out_l" "$out_u" "2" > "$out" 2> "$err"; then
    fenrir-log err "$verbosity" "SM: Script execution has failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

if ! diff --minimal "$in_matrix" "$src"; then
    fenrir-log err "$verbosity" "SM: You have modified source matrix"
    exit 4
fi

if ! diff --minimal "$out_l" "$l"; then
    fenrir-log err "$verbosity" "SM: Wrong L matrix"
    exit 3
fi

if ! diff --minimal "$out_u" "$u"; then
    fenrir-log err "$verbosity" "SM: Wrong U matrix"
    exit 2
fi

fenrir-log succ "$verbosity" "SM: PASSED"
