#! /bin/bash

points=10
verbosity=$1
out="/var/fenrir/out"
err="/var/fenrir/err"
json="/etc/fenrir/mumin.json"

#jq -f task1.jq

if ! jq -f task2.jq "$json" > "$out" 2> "$err"; then
    fenrir-log err "$verbosity" "P2: Script execution has failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err  "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

if ! diff --minimal <(jq '.' "$out") <(jq '.' "/etc/fenrir/p2.json"); then
    fenrir-log err "$verbosity" "P2: Wrong result"
fi

fenrir-add-points "$points"

fenrir-log succ "$verbosity" "P2: PASSED"
